SELECT ARREST_DATE, OFNS_DESC, COUNT(KY_CD) AS 'total_offence'
FROM PERP_SEX 
GROUP BY OFNS_DESC
ORDER BY COUNT(KY_CD) DESC;

SELECT OFNS_DESC, ROUND(AVG(AGE_GROUP),0) AS 'age_average'
from AGE_GROP
WHERE OFNS_DESC LIKE 'RAPE'
ORDER by AVG(AGE_GROUP) desc; 

SELECT PERP_SEX, COUNT(KY_CD) AS 'total_arrest'
FROM PERP_SEX
GROUP BY PERP_SEX;

SELECT *
 FROM (SELECT PD_CD, OFNS_DESC, COUNT(KY_CD) AS 'total_offence' 
 FROM PERP_SEX 
 GROUP BY PD_CD ORDER BY COUNT(KY_CD) DESC) AS avrrst
WHERE OFNS_DESC LIKE 'FELONY ASSAULT' ;

SELECT PERP_RACE.PERP_RACE, PERP_SEX.PD_DESC, COUNT(PERP_SEX.KY_CD) AS 'count_of_arrest'
FROM PERP_RACE 
INNER JOIN PERP_SEX ON PERP_SEX.OFNS_DESC = PERP_RACE.OFNS_DESC
GROUP BY PERP_RACE.PERP_RACE 
ORDER BY COUNT(PERP_SEX.KY_CD) DESC; 

SELECT *
FROM PERP_RACE 
GROUP BY PERP_RACE.PERP_RACE
ORDER BY COUNT(OFNS_DESC) DESC;

ELECT COUNT(KY_CD) AS 'total_arrest', ARREST_DATE, PD_DESC
FROM AGE_GROP 
GROUP BY  ARREST_DATE
WHERE  ARREST_DATE BETWEEN '1/1/24' AND '1/31/2024';



